# Generated by Django 3.2.9 on 2021-11-30 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
